# Generated by Django 5.0.6 on 2024-07-18 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_studentprofile_accno_studentprofile_bankname_and_more'),
        ('athleteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participateevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_event', to='adminapp.event'),
        ),
    ]
