# Generated by Django 5.0.3 on 2024-07-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athleteapp', '0002_alter_participateevent_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='participateevent',
            name='college',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
