# Generated by Django 5.0.3 on 2024-07-25 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0012_alter_sponsorship_is_collegeapproved'),
        ('athleteapp', '0007_delete_participateevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='col', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_event', to='adminapp.event')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
