# Generated by Django 5.0.3 on 2024-07-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athleteapp', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participateevent',
            name='college',
        ),
    ]
