# Generated by Django 4.2.5 on 2024-05-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_remove_studentprofile_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='college_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
