# Generated by Django 4.2.5 on 2024-05-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_customuser_college_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='adm_no',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
