# Generated by Django 5.0.6 on 2024-07-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_event_due_date_studentprofile_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='accno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bankname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ifsc_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
