# Generated by Django 5.0.3 on 2024-07-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_studentprofile_accno_studentprofile_bankname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.URLField(),
        ),
    ]
