# Generated by Django 5.0.3 on 2024-07-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='level',
            field=models.CharField(choices=[('District Level', 'District Level'), ('State Level', 'State Level')], default='District Level', max_length=100),
        ),
    ]
