# Generated by Django 5.0.3 on 2024-07-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_winner_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='achivements',
            field=models.TextField(null=True),
        ),
    ]
