# Generated by Django 5.0.3 on 2024-07-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_studentprofile_achivements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='is_collegeapproved',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Accept', 'Accept'), ('Reject', 'Reject')], default='Waiting', max_length=100),
        ),
    ]
