# Generated by Django 5.0.3 on 2024-07-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_alter_sponsorship_is_collegeapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='intrest',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
