# Generated by Django 5.0.6 on 2024-07-26 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_studentprofile_intrest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
