# Generated by Django 4.1.5 on 2024-07-29 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_sponsorship_college'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='intrest',
            new_name='interest',
        ),
    ]
