# Generated by Django 4.1.5 on 2024-07-30 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_rename_intrest_studentprofile_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.studentprofile'),
        ),
    ]
